/*
 * TerminalDialog.java
 *
 * Created on 5 mars 2008, 12:48
 * 
 *   Copyright (c) 2007, 2008 Florian MAZEN
 *   
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package f4fez.prm80x0.gui.serialterminal;

import f4fez.prm80x0.Controler.SerialListener;

/**
 *
 * @author  fmazen
 */
public class TerminalDialog extends javax.swing.JFrame implements SerialListener {
    
    /** Creates new form TerminalDialog */
    public TerminalDialog() {
        super();
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        terminalTextArea = new javax.swing.JTextArea();
        northPannel = new javax.swing.JPanel();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(f4fez.prm80x0.PRM80X0App.class).getContext().getResourceMap(TerminalDialog.class);
        setTitle(resourceMap.getString("Terminal.title")); // NOI18N
        setName("Terminal"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 450));

        terminalTextArea.setColumns(20);
        terminalTextArea.setEditable(false);
        terminalTextArea.setRows(5);
        terminalTextArea.setName("terminalTextArea"); // NOI18N
        jScrollPane1.setViewportView(terminalTextArea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        northPannel.setName("northPannel"); // NOI18N
        northPannel.setLayout(new javax.swing.BoxLayout(northPannel, javax.swing.BoxLayout.LINE_AXIS));

        clearButton.setText(resourceMap.getString("clearButton.text")); // NOI18N
        clearButton.setName("clearButton"); // NOI18N
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        northPannel.add(clearButton);

        getContentPane().add(northPannel, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        this.terminalTextArea.setText(null);
    }//GEN-LAST:event_clearButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel northPannel;
    private javax.swing.JTextArea terminalTextArea;
    // End of variables declaration//GEN-END:variables

    public void dataSent(String data) {
        //this.terminalTextArea.append(data);
    }

    public void dataReceived(String data) {
        this.terminalTextArea.append(data);
    }
    
}
