/*
 * ConfigurationDialog.java
 *
 * Created on 17 février 2009, 21:28
 */

package f4fez.prm80x0.gui;

import f4fez.prm80x0.Controler.CommunicationException;
import f4fez.prm80x0.Controler.Controler;
import f4fez.prm80x0.VirtualDeviceFirmware;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author  f4fez
 */
public class ConfigurationDialog extends javax.swing.JDialog {

    private VirtualDeviceFirmware vdf;

    /** Creates new form ConfigurationDialog */
    public ConfigurationDialog(java.awt.Frame parent, VirtualDeviceFirmware vdf) {
        super(parent, true);
        initComponents();
        this.vdf = vdf;
        try {
            float pllStep = ((float)this.vdf.getPRMControler().getPLLStep()) / 1000f;
            float shift = ((float)this.vdf.getPRMControler().getTxFrequencyShift()) /1000f;
            int scanSpeed = this.vdf.getPRMControler().getScanSpeed();
            this.pllStepComboBox.setSelectedItem(Float.toString(pllStep));
            this.shiftComboBox.setSelectedItem(Float.toString(shift));
            this.scanSpeedSpinner.setValue(scanSpeed);
            String version;
            if (this.vdf.getPRMControler().getPRMType() == Controler.PRM8060)
                version = "PRM8060 ";
            else
                version = "PRM8070 ";
            version += "V"+Integer.toString(this.vdf.getPRMControler().getMajorFirmwareVersion()) + "." + Integer.toString(this.vdf.getPRMControler().getMinorFirmwareVersion());

            this.versionTextField.setText(version);

        } catch (CommunicationException ex) {
            Logger.getLogger(ConfigurationDialog.class.getName()).log(Level.WARNING, null, ex);
            JOptionPane.showMessageDialog(this, "Erreur de connexion : "+ex.getMessage(), "Erreur de connexion", JOptionPane.ERROR_MESSAGE);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pllStepComboBox = new javax.swing.JComboBox();
        shiftComboBox = new javax.swing.JComboBox();
        scanSpeedSpinner = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        versionTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(f4fez.prm80x0.PRM80X0App.class).getContext().getResourceMap(ConfigurationDialog.class);
        setTitle(resourceMap.getString("Configuration.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(300, 118));
        setName("Configuration"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setMinimumSize(new java.awt.Dimension(300, 189));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 210));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 65, -1, -1));

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 105, -1, -1));

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 145, -1, -1));

        pllStepComboBox.setEditable(true);
        pllStepComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "6.25", "12.5", "25" }));
        pllStepComboBox.setSelectedIndex(1);
        pllStepComboBox.setName("pllStepComboBox"); // NOI18N
        jPanel1.add(pllStepComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 100, -1));

        shiftComboBox.setEditable(true);
        shiftComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "600", "1600", "7600" }));
        shiftComboBox.setName("shiftComboBox"); // NOI18N
        jPanel1.add(shiftComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 100, -1));

        scanSpeedSpinner.setName("scanSpeedSpinner"); // NOI18N
        jPanel1.add(scanSpeedSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 100, -1));

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, -1));

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 100, -1));

        jLabel4.setText(resourceMap.getString("versionLabel.text")); // NOI18N
        jLabel4.setName("versionLabel"); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, -1, -1));

        versionTextField.setText(resourceMap.getString("versionTextField.text")); // NOI18N
        versionTextField.setEnabled(false);
        versionTextField.setName("versionTextField"); // NOI18N
        jPanel1.add(versionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 140, -1));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox pllStepComboBox;
    private javax.swing.JSpinner scanSpeedSpinner;
    private javax.swing.JComboBox shiftComboBox;
    private javax.swing.JTextField versionTextField;
    // End of variables declaration//GEN-END:variables

}
